//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeRoles = new HashSet<EmployeeRole>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
    }
}
